services:
  yaulta:
    build: .
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      CAPTURED_INTERFACE: "${YAULTA_CAPTURED_INTERFACE}"
      NATS_MASTER_ADDR: "${YAUlTA_NATS_MASTER_ADDR}"
      NATS_NODE_ID: "${YAULTA_NATS_NODE_ID}"
      NATS_SUBJECT: "${YAULTA_NATS_SUBJECT}"
    volumes:
      - ./pcap:/pcap
